os:
  - linux
  - osx
language: generic
sudo: required
dist: xenial
osx_image: xcode9
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
  - sudo apt update && sudo apt install libnanomsg-dev --yes
cache:
    directories:
        - $HOME/.swiftenv
script:
  - swift test
