os:
  - linux
  - osx
language: generic
sudo: required
dist: trusty
osx_image: xcode9
install:
  - eval "$(curl -sL https://swiftenv.fuller.li/install.sh)"
cache:
    directories:
        - $HOME/.swiftenv
        - $HOME/.nanomsg
script:
  - swift test
