version: 2
general:
  branches:
    ignore:
      - gh-pages
jobs:
  build:
    docker:
      - image: autozimu/nanomsg.swift
    steps:
      - checkout
      - run: swift build
      - run: swift test
